# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e293e939ba8a57f903cc5934d418c85257d1768aaf0d056e583d333454d12cfd8de310b85469cb6874566e637e72f5074902d147320a0ab39cb8b56f7088b1cc

test:
  secret_key_base: d1fd9590c786fc155ff672ef6985a40d3587b034632eb48e943a65121f904ab229e7683b72018ffd7dac93a3e0f38dd4f158ef4c810eedb1f64a428a8aae2813

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
